{{- if and .Values.aspspMock.enabled .Values.aspspMock.db.persistence.enabled .Values.pvcMange }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ template "psd2.fullname" .  }}-mongo-db-0
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: keycloak-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- with .Values.postgres.persistence.storageClass }}
  storageClassName: {{ . | quote }}
{{- end }}
{{- end }}
