{{- if .Values.keycloak.enabled }}
{{- if not .Values.keycloak.image.stream }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "psd2.fullname" . }}-keycloak
  labels:
{{ include "psd2.labels" . | indent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: {{ .Values.keycloak.image.name }}{{ eq (substr 0 1 .Values.keycloak.image.tag) "@" | ternary "" ":" }}{{ .Values.keycloak.image.tag }}
    referencePolicy:
      type: {{ .Values.pullThrough | ternary "Local" "Source" }}
{{- end }}
{{- end }}
