{{ if .Values.cmsPortal.enabled }}
---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.cmsPortal.serviceAnnotations }}
   annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "psd2.fullname" . }}-cmsportal
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: cmsPortal
    app: aspsp-mock
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
{{ include "psd2.matchLabels" . | indent 4 }}
    app.kubernetes.io/component: cmsPortal
{{- end }}
