{{- if and .Values.postgres.enabled .Values.postgres.backup.enabled .Values.keycloak.db.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "psd2.fullname" . }}-keycloak-backup
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: keycloak-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.backup.persistence.size | quote }}
{{- with .Values.postgres.backup.persistence.storageClass }}
  storageClassName: {{ . | quote }}
{{- end }}
{{- if and .Values.cms.enabled .Values.postgres.backup.enabled .Values.cms.db.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "psd2.fullname" . }}-cms-backup
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: cms-backup
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.backup.persistence.size | quote }}
{{- with .Values.postgres.backup.persistence.storageClass }}
  storageClassName: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
