{{- if and .Values.postgres.metrics.enabled .Values.postgres.metrics.customMetrics.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "psd2.fullname" . }}-postgresql-metrics
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: pg-db
data:
  custom-metrics.yaml: {{ toYaml .Values.postgres.metrics.customMetrics.value | quote }}
{{- end }}
