{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled .Values.keycloak.enabled .Values.pvcMange }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ template "psd2.fullname" .  }}-keycloak-db-0
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: keycloak-db
    app: aspsp-mock
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- with .Values.postgres.persistence.storageClass }}
  storageClassName: {{ . | quote }}
{{- end }}
{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled .Values.cms.enabled .Values.pvcMange }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{ template "psd2.fullname" .  }}-cms-db-0
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: cms-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- with .Values.postgres.persistence.storageClass }}
  storageClassName: {{ . | quote }}
{{- end }}
{{- end }}
{{- end }}
