{{- if and .Values.xs2a.enabled (not .Values.xs2a.image.stream) }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "psd2.fullname" . }}-xs2a
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: xs2a
spec:
  lookupPolicy:
    local: false
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: {{ .Values.xs2a.image.name }}{{ eq (substr 0 1 .Values.xs2a.image.tag) "@" | ternary "" ":" }}{{ .Values.xs2a.image.tag }}
    referencePolicy:
        type: {{ .Values.pullThrough | ternary "Local" "Source" }}
{{- end }}
