{{ if and .Values.cms.enabled (not .Values.cms.image.stream) }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ template "psd2.fullname" . }}-cms
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: ConsentManagementSystem
    app: consent-management-system
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: {{ .Values.cms.image.name }}{{ eq (substr 0 1 .Values.cms.image.tag) "@" | ternary "" ":" }}{{ .Values.cms.image.tag }}
      referencePolicy:
        type: {{ .Values.pullThrough | ternary "Local" "Source" }}
{{- end }}

