{{- if and .Values.keycloak.enabled (eq .Values.keycloak.dbVendor "postgres") }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "psd2.fullname" . }}-keycloak-db-hs"
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: keycloak-db
    app: aspsp-mock
spec:
  sessionAffinity: ClientIP
  # StatefulSets require headless services
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
{{ include "psd2.matchLabels" . | indent 4 }}
    app.kubernetes.io/component: keycloak-db
---
apiVersion: v1
kind: Service
metadata:
{{- with .Values.postgres.serviceAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: "{{ template "psd2.fullname" . }}-keycloak-db"
  labels:
{{ include "psd2.labels" . | indent 4 }}
    app.kubernetes.io/component: keycloak-db
spec:
  sessionAffinity: ClientIP
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
  selector:
{{ include "psd2.matchLabels" . | indent 4 }}
    app.kubernetes.io/component: keycloak-db
{{- end }}
